---
title: "Lesson 6 Creating R packages"
---

<div class="question">

Exercise 6

Go over this <a href="https://r-pkgs.org/whole-game.html">demo</a>. It is a chapter of the booklet on R-packages written by Hadley Wickham and hosted as a bookdown project here.

Execute all the steps in the demo and publish your version of his {foofactors} package as a Github repo in your Github account.

To accomplish this:

1. Start with creating a repo in your account called foofactors.
2. Initiate a new RStudio project using the link to your foofactors Github repo
3. Close this RStudio project.
4. From the R console (while not inside any RStudio project) execute the following steps
5. Initiate an R package by running usethis::create_package("./foofactors") from the R Console. R will ask you to overwrite the foofactors.Rproj file, you should choose ‘yes’
6. A new RStudio session will start and you will find yourself inside your newly created {foofactors} package.

If you did things properly this is what you see in the console after following all the steps above (again: be sure you run this outside an Rstudio project). You are now ready to follow the rest of the ‘Whole Game’ demo as mentioned above (here is the link again:)
```{r}
#| eval: false
usethis::create_package("./foofactors")
√ Setting active project to 'C:/Users/mteunis/workspaces/foofactors'
√ Creating 'R/'
√ Writing 'DESCRIPTION'
Package: foofactors
Title: What the Package Does (One Line, Title Case)
Version: 0.0.0.9000
Authors@R (parsed):
   * First Last <first.last@example.com> [aut, cre] (YOUR-ORCID-ID)
Description: What the package does (one paragraph).
License: `use_mit_license()`, `use_gpl3_license()` or friends to
   pick a license
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.1
√ Writing 'NAMESPACE'
Overwrite pre-existing file 'foofactors.Rproj'?

1: Absolutely not
2: Not now
3: Absolutely

Selection: 3
√ Writing 'foofactors.Rproj'
√ Adding '^foofactors\\.Rproj$' to '.Rbuildignore'
√ Adding '^\\.Rproj\\.user$' to '.Rbuildignore'
√ Opening 'C:/Users/mteunis/workspaces/foofactors/' in new RStudio session
√ Setting active project to '<no active project>'
> 
```
</div class="question">

