project:
  type: website

website:
  title: "Quarto_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    - title: "Tutorials"
      style: "docked"
      background: light
      contents: 
        - about.qmd
        - index.qmd
        - test2.qmd
        - test3.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



